# Generated by Django 4.1.2 on 2022-12-18 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pensione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_user', to=settings.AUTH_USER_MODEL, verbose_name='client_user'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker_user', to=settings.AUTH_USER_MODEL, verbose_name='worker_user'),
        ),
    ]
