# Generated by Django 4.1.2 on 2022-12-20 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pensione', '0002_alter_client_client_user_alter_worker_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
