# Generated by Django 4.1.2 on 2022-10-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(db_column='ID_category', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='categoryName', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id_choice', models.AutoField(db_column='ID_choice', primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(db_column='ID_client', primary_key=True, serialize=False)),
                ('client_name', models.CharField(db_column='clientName', max_length=30)),
                ('client_phone', models.CharField(db_column='clientPhone', max_length=20)),
                ('client_login', models.CharField(db_column='clientLogin', max_length=30, unique=True)),
                ('client_password', models.CharField(db_column='clientPassword', max_length=30)),
                ('social_card_number', models.IntegerField(db_column='socialCardNumber', unique=True)),
                ('client_address', models.CharField(db_column='clientAddress', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id_date', models.AutoField(db_column='ID_date', primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id_manager', models.AutoField(db_column='ID_manager', primary_key=True, serialize=False)),
                ('manager_name', models.CharField(db_column='managerName', max_length=20, unique=True)),
                ('manager_phone', models.CharField(db_column='managerPhone', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(db_column='ID_status', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id_worker', models.AutoField(db_column='ID_worker', primary_key=True, serialize=False)),
                ('worker_name', models.CharField(db_column='workerName', max_length=30)),
                ('worker_phone', models.CharField(db_column='workerPhone', max_length=20)),
                ('worker_type', models.CharField(db_column='workerType', max_length=30)),
                ('photo', models.CharField(blank=True, db_column='photo', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id_service', models.AutoField(db_column='ID_service', primary_key=True, serialize=False)),
                ('service_name', models.CharField(db_column='serviceName', max_length=30)),
                ('price', models.IntegerField(blank=True, db_column='price', null=True)),
                ('image', models.CharField(blank=True, db_column='image', max_length=100, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=200, null=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(db_column='ID_order', primary_key=True, serialize=False)),
                ('id_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.choice')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.client')),
                ('id_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.manager')),
                ('id_orderDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.date')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.status')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.services'),
        ),
        migrations.AddField(
            model_name='choice',
            name='id_serviceDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.date'),
        ),
        migrations.AddField(
            model_name='choice',
            name='id_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pension.workers'),
        ),
    ]
